---
- name: show run
  raw: "show running-config"
  register: result
  changed_when: false

- name: Backup
  ansible.builtin.copy:
    content: "{{ result.stdout_lines |join('\n') }}"
    dest: "backups/{{ inventory_hostname }}.conf"
    mode: '0600'
  when: result is defined
  delegate_to: localhost

- name: clear config
  shell: sed -i '/\[K/d' "backups/{{ inventory_hostname }}.conf"
  delegate_to: localhost
  changed_when: false
  args:
    executable: /usr/bin/bash
