---
#ansible_connection: "ssh"
ansible_ssh_user: "admin"
ansible_ssh_pass: "!pass"

ansible_connection: ansible.netcommon.network_cli
ansible_network_os: community.network.routeros
ansible_user: "admin"
ansible_password: "!pass"
ansible_become: yes
ansible_become_method: enable
ansible_become_password: "!pass"
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q bastion01"'