# Generated by Django 4.1 on 2022-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, verbose_name='Имя')),
                ('usserSurname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('UserPatronymic', models.CharField(max_length=100, verbose_name='Отчество')),
            ],
        ),
    ]
