# Generated by Django 4.1 on 2022-09-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usserSurname',
            new_name='userSurname',
        ),
    ]
