---

- name: check OS
  assert:
    that: "ansible_os_family == 'Debian'"
    fail_msg: "Wrong operating system!"
    success_msg: "Suitable operating system"

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: install MySQL
  include_tasks: MySQL.yml

- name: install Nginx
  include_tasks: nginx.yml

- name: install php-fpm
  include_tasks: php-fpm.yml

- name: WP
  include_tasks: WP.yml
