---

- name: Installing Mysql  and dependencies
  package:
    name:
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev
    state: present
    update_cache: true

  become: true
- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: true
- name: creating mysql user (medium_post)
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
- name: creating medium_db
  mysql_db:
    name: "{{ db_name }}"
    state: present
- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: true
  notify:
    - Restart mysql

- name: Restart mysql
  service:
    name: mysql
    state: restarted
