---
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: restart php-fpm
  service:
    name: php7.4-fpm
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted